# Generated by Django 5.0.3 on 2024-03-19 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_profile_address1_remove_profile_address2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpost', to='user.profile'),
        ),
    ]
