# Generated by Django 5.0.3 on 2024-03-21 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_post_image_alter_post_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='file',
            new_name='video',
        ),
    ]
